# Generated by Django 3.0.2 on 2020-01-10 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='contatos',
            name='endereço',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AddField(
            model_name='contatos',
            name='telefone_celular',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='contatos',
            name='telefone_residencia',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='contatos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
