# Generated by Django 3.0.2 on 2020-01-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_auto_20200110_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='telefone_celular',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='contatos',
            name='telefone_residencia',
            field=models.CharField(max_length=9),
        ),
    ]
