# Generated by Django 3.0.2 on 2020-01-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_auto_20200110_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='email',
            field=models.EmailField(help_text='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contatos',
            name='telefone_celular',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='contatos',
            name='telefone_residencia',
            field=models.CharField(max_length=11),
        ),
    ]
