# Generated by Django 3.0.2 on 2020-01-10 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_auto_20200110_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contatos',
            options={'verbose_name_plural': 'Contatos'},
        ),
    ]
