# Generated by Django 3.0.2 on 2020-01-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0006_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
