# Generated by Django 3.0.2 on 2020-01-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0010_auto_20200113_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
