# Generated by Django 3.0.2 on 2020-01-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0011_auto_20200113_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='telefone_celular',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contatos',
            name='telefone_residencia',
            field=models.CharField(max_length=30),
        ),
    ]
