# Generated by Django 3.0.2 on 2020-01-28 01:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0013_auto_20200123_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='telefone_celular',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='contatos',
            name='telefone_residencia',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
