# Generated by Django 3.0.2 on 2020-01-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0014_auto_20200127_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='email',
            field=models.EmailField(help_text='example@example.com', max_length=254, null=True),
        ),
    ]
