# Generated by Django 3.0.2 on 2020-01-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0015_auto_20200127_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='email',
            field=models.EmailField(blank=True, help_text='example@example.com', max_length=254, null=True),
        ),
    ]
