# Generated by Django 3.0.2 on 2020-01-28 02:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0016_auto_20200127_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='telefone_residencia',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
